cc_library(
    name = "opencv",
    srcs = glob(["lib/x86_64-linux-gnu/libopencv_core.so*",
                 "lib/x86_64-linux-gnu/libopencv_highgui.so*",
                 "lib/x86_64-linux-gnu/libopencv_imgcodecs.so*",
                 "lib/x86_64-linux-gnu/libopencv_imgproc.so*",
                 "lib/x86_64-linux-gnu/libopencv_video.so*",
                 "lib/x86_64-linux-gnu/libopencv_videoio.so*",
                 "lib/x86_64-linux-gnu/blas/libblas.so*",
                 "lib/x86_64-linux-gnu/lapack/liblapack.so*",
                 ]),
    hdrs = glob(["include/opencv2/**/*.h*"]),
    includes = ["include/opencv2"],
    visibility = ["//visibility:public"], 
    linkstatic = 1,
)

cc_library(
    name = "opencv_GPUDec",
    srcs = glob(["local/opencv/install/lib/libopencv_core.so*",
                 "local/opencv/install/lib/libopencv_highgui.so*",
                 "local/opencv/install/lib/libopencv_imgcodecs.so*",
                 "local/opencv/install/lib/libopencv_imgproc.so*",
                 "local/opencv/install/lib/libopencv_video.so*",
                 "local/opencv/install/lib/libopencv_videoio.so*",
                 "local/opencv/install/lib/libopencv_cudacodec.so*",
                 "lib/x86_64-linux-gnu/blas/libblas.so*",
                 "lib/x86_64-linux-gnu/lapack/liblapack.so*",
                 ]),
    hdrs = glob(["local/opencv/install/include/opencv4/opencv2/**/*.h*"]),
    includes = ["local/opencv/install/include/opencv4"],
    visibility = ["//visibility:public"], 
    linkstatic = 1,
)
