cc_library(
    name = "lib_sample_app",
    srcs = ["sample_lib.cpp"],
    hdrs = ["sample_lib.h"],
    defines = ["ENABLE_DEBUG"],
    visibility = ["//visibility:public"],
    copts = ["-fPIC", "-g"],
)
